services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: lester
        uid: 1001
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lester-portfolio
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
